// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package view

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type Data interface {
	IsData()
	GetID() uint64
}

type AuditLog struct {
	ID           uint64    `json:"id"`
	UserID       uint64    `json:"userID"`
	Method       string    `json:"method"`
	RequestInput string    `json:"requestInput"`
	CreatedAt    time.Time `json:"createdAt"`
}

type AuditLogCreateInput struct {
	Method       string `json:"method"`
	UserID       uint64 `json:"userID"`
	RequestInput string `json:"requestInput"`
}

type AuditLogFilterInput struct {
	AuditLog   *AuditLogInput   `json:"auditLog,omitempty"`
	BaseFilter *BaseFilterInput `json:"baseFilter,omitempty"`
}

type AuditLogInput struct {
	ID     *uint64 `json:"id,omitempty"`
	Method *string `json:"method,omitempty"`
	UserID *uint64 `json:"userID,omitempty"`
}

type BaseFilterInput struct {
	IDs              []uint64   `json:"IDs,omitempty"`
	SearchIn         *string    `json:"searchIn,omitempty"`
	Keyword          *string    `json:"keyword,omitempty"`
	CreatedAtLt      *uint64    `json:"createdAtLT,omitempty"`
	CreatedAtLte     *uint64    `json:"createdAtLTE,omitempty"`
	CreatedAtGt      *uint64    `json:"createdAtGT,omitempty"`
	CreatedAtGte     *uint64    `json:"createdAtGTE,omitempty"`
	SortField        *string    `json:"sortField,omitempty"`
	SortType         *SortType  `json:"sortType,omitempty"`
	RangeField       *string    `json:"rangeField,omitempty"`
	RangeType        *RangeType `json:"rangeType,omitempty"`
	LessThan         *int64     `json:"lessThan,omitempty"`
	LessThanEqual    *int64     `json:"lessThanEqual,omitempty"`
	GreaterThan      *int64     `json:"greaterThan,omitempty"`
	GreaterThanEqual *int64     `json:"greaterThanEqual,omitempty"`
}

type Claims struct {
	// id
	ID uint64 `json:"id"`
	// 帳號類型
	AccountType AccountType `json:"accountType"`
	// 狀態
	Status UserStatus `json:"status"`
	// 用户名
	Username string `json:"username"`
	// 別名（聊天室顯示用）
	AliasName string `json:"aliasName"`
	// 頭像鏈結
	AvatarURL  string           `json:"avatarURL"`
	Whitelists []*UserWhitelist `json:"whitelists"`
	Menu       []*Menu          `json:"menu"`
}

type Common struct {
	CreatorID   *uint64    `json:"creatorID,omitempty"`
	CreatorName *string    `json:"creatorName,omitempty"`
	CreatedAt   *time.Time `json:"createdAt,omitempty"`
	UpdaterID   *uint64    `json:"updaterID,omitempty"`
	UpdaterName *string    `json:"updaterName,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
}

type CreateCommonUserReqInput struct {
	Username    string      `json:"username"`
	Password    string      `json:"password"`
	AccountType AccountType `json:"accountType"`
}

type CreateCommonUserResp struct {
	User *User `json:"user"`
}

type CreateUploadURLInput struct {
	ExpireSec *int64           `json:"expireSec,omitempty"`
	Files     []*FileInfoInput `json:"files"`
}

type CreateUploadURLResp struct {
	Files []*FileInfo `json:"files"`
}

type CreateUserReqInput struct {
	Username    string      `json:"username"`
	Password    string      `json:"password"`
	AccountType AccountType `json:"accountType"`
	AliasName   string      `json:"aliasName"`
}

type CreateUserResp struct {
	User *User `json:"user"`
}

type DataList struct {
	Data []Data `json:"data"`
	Meta *Meta  `json:"meta"`
}

type File struct {
	ID          uint64 `json:"id"`
	Name        string `json:"name"`
	Content     string `json:"content"`
	ContentType string `json:"contentType"`
}

func (File) IsData()            {}
func (this File) GetID() uint64 { return this.ID }

type FileInfo struct {
	FileName  string `json:"fileName"`
	UploadURL string `json:"uploadURL"`
}

type FileInfoInput struct {
	FileName string `json:"fileName"`
	// 檔案大小
	Size int64 `json:"size"`
	// 檔案 MD5 The base64-encoded 128-bit MD5 digest
	Md5 string `json:"md5"`
}

// 黑名單系統
type HostsDeny struct {
	// id
	ID uint64 `json:"id"`
	// ip
	IPAddress string `json:"ipAddress"`
	// 是否啟用
	IsEnabled YesNo `json:"isEnabled"`
	// 備註
	Remark string `json:"remark"`
	// 建立時間
	CreatedAt time.Time `json:"createdAt"`
	// 建立者
	CreateUserID uint64 `json:"createUserID"`
	// 更新時間
	UpdatedAt time.Time `json:"updatedAt"`
	// 更新者
	UpdateUserID uint64 `json:"updateUserID"`
}

type HostsDenyCreateInput struct {
	// IP
	IPAddress string `json:"ipAddress"`
	// 是否啟用
	IsEnabled YesNo `json:"isEnabled"`
	// 備註
	Remark *string `json:"remark,omitempty"`
}

type HostsDenyFilterInput struct {
	HostsDeny  *HostsDenyInput  `json:"hostsDeny,omitempty"`
	BaseFilter *BaseFilterInput `json:"baseFilter,omitempty"`
}

type HostsDenyInput struct {
	// id
	ID *uint64 `json:"id,omitempty"`
	// IP
	IPAddress *string `json:"ipAddress,omitempty"`
	// 是否啟用
	IsEnabled *YesNo `json:"isEnabled,omitempty"`
}

type HostsDenyUpdateInput struct {
	// IP
	IPAddress *string `json:"ipAddress,omitempty"`
	// 是否啟用
	IsEnabled *YesNo `json:"isEnabled,omitempty"`
	// 備註
	Remark *string `json:"remark,omitempty"`
}

type HubClient struct {
	UserID  uint64       `json:"userID"`
	Devices []*HubDevice `json:"devices"`
}

type HubDevice struct {
	Token     string `json:"token"`
	DeviceUID string `json:"deviceUID"`
	RoomID    uint64 `json:"roomID"`
}

type ListAuditLogResp struct {
	AuditLogs []*AuditLog `json:"auditLogs"`
	Meta      *Meta       `json:"meta"`
}

type ListHostsDenyResp struct {
	HostsDenys []*HostsDeny `json:"hostsDenys"`
	Meta       *Meta        `json:"meta"`
}

type ListMetadata struct {
	Count *uint64 `json:"count,omitempty"`
}

type ListRoleResp struct {
	Roles []*Role `json:"roles"`
	Meta  *Meta   `json:"meta"`
}

type ListTagResp struct {
	Tags []*Tag `json:"tags"`
	Meta *Meta  `json:"meta"`
}

type ListUserLoginHistoryResp struct {
	UserLoginHistories []*UserLoginHistory `json:"userLoginHistories"`
	Meta               *Meta               `json:"meta,omitempty"`
}

type ListUserResp struct {
	Users []*User `json:"users"`
	Meta  *Meta   `json:"meta"`
}

type ListUserRoleResp struct {
	UserRoles []*UserRole `json:"userRoles"`
	Meta      *Meta       `json:"meta"`
}

type ListUserTagResp struct {
	UserTags []*UserTag `json:"userTags"`
	Meta     *Meta      `json:"meta"`
}

type ListUserWhitelistResp struct {
	UserWhitelists []*UserWhitelist `json:"userWhitelists"`
	Meta           *Meta            `json:"meta"`
}

type LoginReqInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token     string `json:"token"`
	DeviceUID string `json:"deviceUID"`
	UserAgent string `json:"userAgent"`
}

type Menu struct {
	Name     string  `json:"name"`
	Key      string  `json:"key"`
	SuperKey string  `json:"superKey"`
	Next     []*Menu `json:"next"`
}

type MenuInput struct {
	Key  string       `json:"key"`
	Next []*MenuInput `json:"next"`
}

type Meta struct {
	Total     uint64  `json:"total"`
	Page      *uint64 `json:"page,omitempty"`
	PerPage   *uint64 `json:"perPage,omitempty"`
	TotalPage *uint64 `json:"totalPage,omitempty"`
}

type Mutation struct {
}

type PaginationInput struct {
	Page       *uint64     `json:"page,omitempty"`
	PerPage    *uint64     `json:"perPage,omitempty"`
	OffsetType *OffsetType `json:"offsetType,omitempty"`
	OffsetID   *uint64     `json:"offsetID,omitempty"`
	Limit      *uint64     `json:"limit,omitempty"`
}

type Query struct {
}

type RefreshTokenResp struct {
	Token   string    `json:"token"`
	Expires time.Time `json:"expires"`
}

type Role struct {
	ID                 uint64      `json:"id"`
	Name               string      `json:"name"`
	Authority          []*Menu     `json:"authority"`
	SupportAccountType AccountType `json:"supportAccountType"`
	CreatedAt          time.Time   `json:"createdAt"`
	CreateUserID       uint64      `json:"createUserID"`
	UpdatedAt          time.Time   `json:"updatedAt"`
	UpdateUserID       uint64      `json:"updateUserID"`
}

type RoleCreateInput struct {
	Name               string       `json:"name"`
	SupportAccountType AccountType  `json:"supportAccountType"`
	Authority          []*MenuInput `json:"authority"`
}

type RoleFilterInput struct {
	Role       *RoleInput       `json:"role,omitempty"`
	BaseFilter *BaseFilterInput `json:"baseFilter,omitempty"`
}

type RoleInput struct {
	ID                 *uint64      `json:"id,omitempty"`
	Name               *string      `json:"name,omitempty"`
	SupportAccountType *AccountType `json:"supportAccountType,omitempty"`
}

type RoleUpdateInput struct {
	Name               *string      `json:"name,omitempty"`
	SupportAccountType *AccountType `json:"supportAccountType,omitempty"`
	Authority          []*MenuInput `json:"authority,omitempty"`
}

type Subscription struct {
}

type Tag struct {
	// id
	ID   uint64 `json:"id"`
	Name string `json:"name"`
	// 色碼 # 000000
	RGBHex string `json:"RGBHex"`
	// 是否啟用
	IsEnable     YesNo     `json:"isEnable"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
	CreateUserID uint64    `json:"createUserID"`
	UpdateUserID uint64    `json:"updateUserID"`
}

type TagCreateInput struct {
	Name string `json:"name"`
	// 色碼 # 000000
	RGBHex string `json:"RGBHex"`
}

type TagFilterInput struct {
	Tag        *TagInput        `json:"tag,omitempty"`
	BaseFilter *BaseFilterInput `json:"baseFilter,omitempty"`
}

type TagInput struct {
	ID       *uint64 `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	IsEnable *YesNo  `json:"isEnable,omitempty"`
}

type TagUpdateInput struct {
	Name     *string `json:"name,omitempty"`
	RGBHex   *string `json:"RGBHex,omitempty"`
	IsEnable *YesNo  `json:"isEnable,omitempty"`
}

type User struct {
	// id
	ID uint64 `json:"id"`
	// 帳號類型
	AccountType AccountType `json:"accountType"`
	// 狀態
	Status UserStatus `json:"status"`
	// 用户名
	Username string `json:"username"`
	// 別名（聊天室顯示用)
	AliasName string `json:"aliasName"`
	// 電子郵件
	Email string `json:"email"`
	// 居住地區
	Area string `json:"area"`
	// 備註
	Notes string `json:"notes"`
	// 頭像鏈結
	AvatarURL string `json:"avatarURL"`
	// 最後登陸時間
	LastLoginAt time.Time `json:"lastLoginAt"`
	// 最後登陸的IP
	LastLoginIP string `json:"lastLoginIP"`
	// 是否已刪除
	IsDelete YesNo `json:"isDelete"`
	// 建立时间
	CreatedAt time.Time `json:"createdAt"`
	// 更新時間
	UpdatedAt time.Time `json:"updatedAt"`
	// 更新人
	UpdateUserID uint64           `json:"updateUserID"`
	Roles        []*UserRole      `json:"roles"`
	Whitelists   []*UserWhitelist `json:"whitelists"`
	Tags         []*UserTag       `json:"tags"`
}

type UserAuth struct {
	Token     string `json:"token"`
	DeviceUID string `json:"deviceUID"`
}

type UserFilterInput struct {
	User       *UserInput       `json:"user,omitempty"`
	BaseFilter *BaseFilterInput `json:"baseFilter,omitempty"`
	TagIDs     []uint64         `json:"tagIDs,omitempty"`
	RoleIDs    []uint64         `json:"roleIDs,omitempty"`
}

type UserInput struct {
	// id
	ID *uint64 `json:"id,omitempty"`
	// 帳號類型
	AccountType *AccountType `json:"accountType,omitempty"`
	// 狀態
	Status *UserStatus `json:"status,omitempty"`
	// 用户名
	Username *string `json:"username,omitempty"`
	// 別名（聊天室顯示用）
	AliasName *string `json:"aliasName,omitempty"`
	// 電子郵件
	Email *string `json:"email,omitempty"`
	// 居住地區
	Area *string `json:"area,omitempty"`
	// 備註
	Notes *string `json:"notes,omitempty"`
	// 頭像鏈結
	AvatarURL *string `json:"avatarURL,omitempty"`
}

type UserLoginHistory struct {
	ID                 uint64    `json:"id"`
	UserID             uint64    `json:"userID"`
	IPAddress          string    `json:"ipAddress"`
	Country            string    `json:"country"`
	AdministrativeArea string    `json:"administrativeArea"`
	DeviceOs           DeviceOs  `json:"deviceOS"`
	CreatedAt          time.Time `json:"createdAt"`
}

type UserLoginHistoryFilterInput struct {
	BaseFilter       *BaseFilterInput       `json:"baseFilter,omitempty"`
	UserLoginHistory *UserLoginHistoryInput `json:"userLoginHistory,omitempty"`
}

type UserLoginHistoryInput struct {
	UserID *uint64 `json:"userID,omitempty"`
}

type UserRole struct {
	// id
	ID uint64 `json:"id"`
	// user id
	UserID uint64 `json:"userID"`
	// 角色 id
	RoleID uint64 `json:"roleID"`
	// 是否為管理員
	IsAdmin YesNo `json:"isAdmin"`
	// 創建 user id
	CreateUserID uint64 `json:"createUserID"`
	// 更新 user id
	UpdateUserID uint64 `json:"updateUserID"`
	// 建立时间
	CreatedAt time.Time `json:"createdAt"`
	// 建立时间
	UpdatedAt time.Time `json:"updatedAt"`
	// 角色
	Role *Role `json:"role"`
}

type UserRoleCreateInput struct {
	// user id
	UserID uint64 `json:"userID"`
	// 角色 id
	RoleID uint64 `json:"roleID"`
	// 是否為管理員
	IsAdmin YesNo `json:"isAdmin"`
}

type UserRoleFilterInput struct {
	UserRole   *UserRoleInput   `json:"userRole,omitempty"`
	BaseFilter *BaseFilterInput `json:"baseFilter,omitempty"`
}

type UserRoleInput struct {
	// id
	ID *uint64 `json:"id,omitempty"`
	// user id
	UserID *uint64 `json:"userID,omitempty"`
	// ip 地址
	RoleID *uint64 `json:"roleID,omitempty"`
	// 是否為管理員
	IsAdmin *YesNo `json:"isAdmin,omitempty"`
}

type UserRoleUpdateInput struct {
	RoleID *uint64 `json:"roleID,omitempty"`
}

type UserTag struct {
	// id
	ID           uint64    `json:"id"`
	UserID       uint64    `json:"userID"`
	TagID        uint64    `json:"tagID"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
	CreateUserID uint64    `json:"createUserID"`
	UpdateUserID uint64    `json:"updateUserID"`
	Tag          *Tag      `json:"tag"`
}

type UserTagCreateInput struct {
	UserID uint64 `json:"userID"`
	TagID  uint64 `json:"tagID"`
}

type UserTagFilterInput struct {
	UserTag    *UserTagInput    `json:"userTag,omitempty"`
	BaseFilter *BaseFilterInput `json:"baseFilter,omitempty"`
}

type UserTagInput struct {
	ID     *uint64 `json:"id,omitempty"`
	UserID *uint64 `json:"userID,omitempty"`
	TagID  *uint64 `json:"tagID,omitempty"`
}

type UserTagUpdateInput struct {
	TagID *uint64 `json:"tagID,omitempty"`
}

type UserUpdateInput struct {
	// 狀態
	Status *UserStatus `json:"status,omitempty"`
	// 別名（聊天室顯示用）
	AliasName *string `json:"aliasName,omitempty"`
	// 居住地區
	Area *string `json:"area,omitempty"`
	// 備註
	Notes *string `json:"notes,omitempty"`
	// 頭像鏈結
	AvatarContent *graphql.Upload `json:"avatarContent,omitempty"`
	// 帳戶類型 使用者 / 員工 / 客服
	AccountType *AccountType `json:"accountType,omitempty"`
}

type UserUpdatePasswordInput struct {
	UserID   uint64 `json:"userID"`
	Password string `json:"password"`
}

type UserWhitelist struct {
	// id
	ID uint64 `json:"id"`
	// user id
	UserID uint64 `json:"userID"`
	// ip 地址
	IPAddress string `json:"ipAddress"`
	// 建立时间
	CreatedAt time.Time `json:"createdAt"`
}

type UserWhitelistCreateInput struct {
	UserID    uint64 `json:"userID"`
	IPAddress string `json:"ipAddress"`
}

type UserWhitelistFilterInput struct {
	UserWhitelist *UserWhitelistInput `json:"userWhitelist,omitempty"`
	BaseFilter    *BaseFilterInput    `json:"baseFilter,omitempty"`
}

type UserWhitelistInput struct {
	// id
	ID *uint64 `json:"id,omitempty"`
	// user id
	UserID *uint64 `json:"userID,omitempty"`
	// ip 地址
	IPAddress *string `json:"ipAddress,omitempty"`
}

type UserWhitelistUpdateInput struct {
	IPAddress *string `json:"ipAddress,omitempty"`
}

type AccountType string

const (
	AccountTypeUnknown AccountType = "Unknown"
	// 系統管理員
	AccountTypeAdmin AccountType = "Admin"
	// 系統
	AccountTypeSystem AccountType = "System"
	// 管理員
	AccountTypeManager AccountType = "Manager"
	// 客服
	AccountTypeCustomerService AccountType = "CustomerService"
	// 一般會員
	AccountTypeMember AccountType = "Member"
	// 遊客
	AccountTypeTourist AccountType = "Tourist"
)

var AllAccountType = []AccountType{
	AccountTypeUnknown,
	AccountTypeAdmin,
	AccountTypeSystem,
	AccountTypeManager,
	AccountTypeCustomerService,
	AccountTypeMember,
	AccountTypeTourist,
}

func (e AccountType) IsValid() bool {
	switch e {
	case AccountTypeUnknown, AccountTypeAdmin, AccountTypeSystem, AccountTypeManager, AccountTypeCustomerService, AccountTypeMember, AccountTypeTourist:
		return true
	}
	return false
}

func (e AccountType) String() string {
	return string(e)
}

func (e *AccountType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccountType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccountType", str)
	}
	return nil
}

func (e AccountType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DeviceOs string

const (
	DeviceOsUnknown DeviceOs = "Unknown"
	// IOS
	DeviceOsIos DeviceOs = "IOS"
	// Android
	DeviceOsAndroid DeviceOs = "Android"
	// Windows
	DeviceOsWindows DeviceOs = "Windows"
	// Mac
	DeviceOsMac DeviceOs = "Mac"
	// 其他
	DeviceOsOther DeviceOs = "Other"
)

var AllDeviceOs = []DeviceOs{
	DeviceOsUnknown,
	DeviceOsIos,
	DeviceOsAndroid,
	DeviceOsWindows,
	DeviceOsMac,
	DeviceOsOther,
}

func (e DeviceOs) IsValid() bool {
	switch e {
	case DeviceOsUnknown, DeviceOsIos, DeviceOsAndroid, DeviceOsWindows, DeviceOsMac, DeviceOsOther:
		return true
	}
	return false
}

func (e DeviceOs) String() string {
	return string(e)
}

func (e *DeviceOs) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DeviceOs(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DeviceOS", str)
	}
	return nil
}

func (e DeviceOs) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MoreInformationType string

const (
	MoreInformationTypeUnknown MoreInformationType = "Unknown"
	MoreInformationTypeHTML    MoreInformationType = "HTML"
	MoreInformationTypeURL     MoreInformationType = "URL"
)

var AllMoreInformationType = []MoreInformationType{
	MoreInformationTypeUnknown,
	MoreInformationTypeHTML,
	MoreInformationTypeURL,
}

func (e MoreInformationType) IsValid() bool {
	switch e {
	case MoreInformationTypeUnknown, MoreInformationTypeHTML, MoreInformationTypeURL:
		return true
	}
	return false
}

func (e MoreInformationType) String() string {
	return string(e)
}

func (e *MoreInformationType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MoreInformationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MoreInformationType", str)
	}
	return nil
}

func (e MoreInformationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type OffsetType string

const (
	OffsetTypeUnknown OffsetType = "Unknown"
	OffsetTypeOld     OffsetType = "Old"
	OffsetTypeNew     OffsetType = "New"
)

var AllOffsetType = []OffsetType{
	OffsetTypeUnknown,
	OffsetTypeOld,
	OffsetTypeNew,
}

func (e OffsetType) IsValid() bool {
	switch e {
	case OffsetTypeUnknown, OffsetTypeOld, OffsetTypeNew:
		return true
	}
	return false
}

func (e OffsetType) String() string {
	return string(e)
}

func (e *OffsetType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OffsetType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OffsetType", str)
	}
	return nil
}

func (e OffsetType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Position string

const (
	PositionTop    Position = "Top"
	PositionBottom Position = "Bottom"
	PositionLeft   Position = "Left"
	PositionRight  Position = "Right"
)

var AllPosition = []Position{
	PositionTop,
	PositionBottom,
	PositionLeft,
	PositionRight,
}

func (e Position) IsValid() bool {
	switch e {
	case PositionTop, PositionBottom, PositionLeft, PositionRight:
		return true
	}
	return false
}

func (e Position) String() string {
	return string(e)
}

func (e *Position) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Position(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Position", str)
	}
	return nil
}

func (e Position) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type RangeType string

const (
	RangeTypeByDateTime RangeType = "ByDateTime"
	RangeTypeByNumber   RangeType = "ByNumber"
)

var AllRangeType = []RangeType{
	RangeTypeByDateTime,
	RangeTypeByNumber,
}

func (e RangeType) IsValid() bool {
	switch e {
	case RangeTypeByDateTime, RangeTypeByNumber:
		return true
	}
	return false
}

func (e RangeType) String() string {
	return string(e)
}

func (e *RangeType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RangeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RangeType", str)
	}
	return nil
}

func (e RangeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SortType string

const (
	SortTypeUnknown SortType = "Unknown"
	SortTypeAsc     SortType = "ASC"
	SortTypeDesc    SortType = "DESC"
)

var AllSortType = []SortType{
	SortTypeUnknown,
	SortTypeAsc,
	SortTypeDesc,
}

func (e SortType) IsValid() bool {
	switch e {
	case SortTypeUnknown, SortTypeAsc, SortTypeDesc:
		return true
	}
	return false
}

func (e SortType) String() string {
	return string(e)
}

func (e *SortType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortType", str)
	}
	return nil
}

func (e SortType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserStatus string

const (
	UserStatusUnknown UserStatus = "Unknown"
	// 未驗證
	UserStatusUnVerified UserStatus = "UnVerified"
	// 啟用中
	UserStatusActived UserStatus = "Actived"
	// 鎖定
	UserStatusLocked UserStatus = "Locked"
	// 停用中
	UserStatusDisabled UserStatus = "Disabled"
	// 已刪除
	UserStatusDeleted UserStatus = "Deleted"
)

var AllUserStatus = []UserStatus{
	UserStatusUnknown,
	UserStatusUnVerified,
	UserStatusActived,
	UserStatusLocked,
	UserStatusDisabled,
	UserStatusDeleted,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusUnknown, UserStatusUnVerified, UserStatusActived, UserStatusLocked, UserStatusDisabled, UserStatusDeleted:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type YesNo string

const (
	YesNoUnknown YesNo = "Unknown"
	YesNoYes     YesNo = "Yes"
	YesNoNo      YesNo = "No"
)

var AllYesNo = []YesNo{
	YesNoUnknown,
	YesNoYes,
	YesNoNo,
}

func (e YesNo) IsValid() bool {
	switch e {
	case YesNoUnknown, YesNoYes, YesNoNo:
		return true
	}
	return false
}

func (e YesNo) String() string {
	return string(e)
}

func (e *YesNo) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = YesNo(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid YesNo", str)
	}
	return nil
}

func (e YesNo) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
