package platform

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"boyi/pkg/delivery/graph/view"
	"context"
	"fmt"
)

// CreateAgent is the resolver for the createAgent field.
func (r *mutationResolver) CreateAgent(ctx context.Context, in view.AgentCreateInput) (uint64, error) {
	panic(fmt.Errorf("not implemented: CreateAgent - createAgent"))
}

// UpdateAgent is the resolver for the updateAgent field.
func (r *mutationResolver) UpdateAgent(ctx context.Context, filter view.AgentFilterInput, in view.AgentUpdateInput) (uint64, error) {
	panic(fmt.Errorf("not implemented: UpdateAgent - updateAgent"))
}

// DeleteAgent is the resolver for the deleteAgent field.
func (r *mutationResolver) DeleteAgent(ctx context.Context, filter view.AgentFilterInput) (uint64, error) {
	panic(fmt.Errorf("not implemented: DeleteAgent - deleteAgent"))
}

// CreateGeneralAgent is the resolver for the createGeneralAgent field.
func (r *mutationResolver) CreateGeneralAgent(ctx context.Context, in view.GeneralAgentCreateInput) (uint64, error) {
	panic(fmt.Errorf("not implemented: CreateGeneralAgent - createGeneralAgent"))
}

// UpdateGeneralAgent is the resolver for the updateGeneralAgent field.
func (r *mutationResolver) UpdateGeneralAgent(ctx context.Context, filter view.GeneralAgentFilterInput, in view.GeneralAgentUpdateInput) (uint64, error) {
	panic(fmt.Errorf("not implemented: UpdateGeneralAgent - updateGeneralAgent"))
}

// DeleteGeneralAgent is the resolver for the deleteGeneralAgent field.
func (r *mutationResolver) DeleteGeneralAgent(ctx context.Context, filter view.GeneralAgentFilterInput) (uint64, error) {
	panic(fmt.Errorf("not implemented: DeleteGeneralAgent - deleteGeneralAgent"))
}

// ListAgent is the resolver for the listAgent field.
func (r *queryResolver) ListAgent(ctx context.Context, filter *view.AgentFilterInput, pagination *view.PaginationInput) (*view.ListAgentResp, error) {
	panic(fmt.Errorf("not implemented: ListAgent - listAgent"))
}

// ListGeneralAgent is the resolver for the listGeneralAgent field.
func (r *queryResolver) ListGeneralAgent(ctx context.Context, filter *view.GeneralAgentFilterInput, pagination *view.PaginationInput) (*view.ListGeneralAgentResp, error) {
	panic(fmt.Errorf("not implemented: ListGeneralAgent - listGeneralAgent"))
}
