package platform

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"boyi/pkg/delivery/graph/view"
	"context"
	"fmt"
)

// ListGamePlayer is the resolver for the listGamePlayer field.
func (r *queryResolver) ListGamePlayer(ctx context.Context, filter view.GamePlayerFilterInput, pagination *view.PaginationInput) (*view.ListGamePlayerResp, error) {
	panic(fmt.Errorf("not implemented: ListGamePlayer - listGamePlayer"))
}

// ListGameTransferRecord is the resolver for the listGameTransferRecord field.
func (r *queryResolver) ListGameTransferRecord(ctx context.Context, filter view.GameTransferRecordFilterInput, pagination *view.PaginationInput) (*view.ListGameTransferRecordResp, error) {
	panic(fmt.Errorf("not implemented: ListGameTransferRecord - listGameTransferRecord"))
}
