package platform

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"boyi/internal/claims"
	"boyi/pkg/delivery/graph/view"
	"boyi/pkg/model/enums/types"
	"context"
)

// ListMenu is the resolver for the listMenu field.
func (r *queryResolver) ListMenu(ctx context.Context) ([]*view.Menu, error) {
	var resp []*view.Menu
	_, err := claims.GetClaims(ctx)
	if err != nil {
		return nil, err
	}
	result := r.menuSvc.GetParsedMenuTree(claims.Claims{
		AccountType: uint64(types.AccountType__System),
	})

	resp = make([]*view.Menu, 0, len(result))
	viewMenu := make([]view.Menu, len(result))
	for i := range result {
		resp = append(resp, viewMenu[i].FromDTO(result[i]))
	}
	return resp, nil
}
