package platform

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"boyi/pkg/delivery/graph/view"
	"context"
	"fmt"
)

// CreateHostsDeny is the resolver for the createHostsDeny field.
func (r *mutationResolver) CreateHostsDeny(ctx context.Context, in view.HostsDenyCreateInput) (*view.HostsDeny, error) {
	panic(fmt.Errorf("not implemented: CreateHostsDeny - createHostsDeny"))
}

// UpdateHostsDeny is the resolver for the updateHostsDeny field.
func (r *mutationResolver) UpdateHostsDeny(ctx context.Context, filter view.HostsDenyFilterInput, in view.HostsDenyUpdateInput) (*view.HostsDeny, error) {
	panic(fmt.Errorf("not implemented: UpdateHostsDeny - updateHostsDeny"))
}

// DeleteHostsDeny is the resolver for the deleteHostsDeny field.
func (r *mutationResolver) DeleteHostsDeny(ctx context.Context, filter view.HostsDenyFilterInput) (uint64, error) {
	panic(fmt.Errorf("not implemented: DeleteHostsDeny - deleteHostsDeny"))
}

// GetHostsDeny is the resolver for the getHostsDeny field.
func (r *queryResolver) GetHostsDeny(ctx context.Context, filter view.HostsDenyFilterInput) (*view.HostsDeny, error) {
	panic(fmt.Errorf("not implemented: GetHostsDeny - getHostsDeny"))
}

// ListHostsDeny is the resolver for the listHostsDeny field.
func (r *queryResolver) ListHostsDeny(ctx context.Context, filter *view.HostsDenyFilterInput, pagination *view.PaginationInput) (*view.ListHostsDenyResp, error) {
	panic(fmt.Errorf("not implemented: ListHostsDeny - listHostsDeny"))
}
