apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- config.yaml
- svc.yaml
images:
- name: spinach.azurecr.io/boyi/server
  newTag: 146ab8d
configMapGenerator:
- behavior: replace
  files:
  - app_dev.properties
  name: boyi-server-config
