apiVersion: v1
kind: Service
metadata:
  name: boyi-server-svc
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  - port: 8090
    name: grpc
    targetPort: 8090
  selector:
    app: boyi-server