package merchant

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"boyi/pkg/delivery/graph/view"
	"boyi/pkg/infra/ctxutil"
	"context"
	"fmt"
)

// Login is the resolver for the Login field.
func (r *mutationResolver) Login(ctx context.Context, in view.LoginReqInput) (*view.LoginResp, error) {
	var resp view.LoginResp

	result, err := r.authSvc.MerchantLogin(ctx, in.ConvertToVo(ctx))
	if err != nil {
		return nil, err
	}
	resp = view.LoginResp{
		Token:     result.Token,
		UserAgent: ctxutil.GetUserAgentFromContext(ctx),
		DeviceUID: ctxutil.GetDeviceOSFronContext(ctx),
	}
	return resp.FromClaims(result), nil
}

// Logout is the resolver for the Logout field.
func (r *mutationResolver) Logout(ctx context.Context) (uint64, error) {
	panic(fmt.Errorf("not implemented: Logout - Logout"))
}

// Me is the resolver for the Me field.
func (r *queryResolver) Me(ctx context.Context) (*view.Claims, error) {
	panic(fmt.Errorf("not implemented: Me - Me"))
}
